snd-soc-smartpa-aw882xx-objs := aw882xx.o aw882xx_monitor.o aw882xx_init.o aw882xx_dsp.o aw882xx_device.o aw882xx_calib.o aw882xx_bin_parse.o aw882xx_spin.o
obj-$(CONFIG_SND_SMARTPA_AW882XX) += snd-soc-smartpa-aw882xx.o
